/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConcreteDrivewaysRouteImport } from './routes/concrete-driveways'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FencingRouteImport } from './routes/fencing'
import { Route as PaintingRouteImport } from './routes/painting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteDrivewaysRoute = ConcreteDrivewaysRouteImport.update({
  id: '/concrete-driveways',
  path: '/concrete-driveways',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FencingRoute = FencingRouteImport.update({
  id: '/fencing',
  path: '/fencing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingRoute = PaintingRouteImport.update({
  id: '/painting',
  path: '/painting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concrete-driveways': typeof ConcreteDrivewaysRoute
  '/contact': typeof ContactRoute
  '/fencing': typeof FencingRoute
  '/painting': typeof PaintingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concrete-driveways': typeof ConcreteDrivewaysRoute
  '/contact': typeof ContactRoute
  '/fencing': typeof FencingRoute
  '/painting': typeof PaintingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concrete-driveways': typeof ConcreteDrivewaysRoute
  '/contact': typeof ContactRoute
  '/fencing': typeof FencingRoute
  '/painting': typeof PaintingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/concrete-driveways'
    | '/contact'
    | '/fencing'
    | '/painting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/concrete-driveways'
    | '/contact'
    | '/fencing'
    | '/painting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/concrete-driveways'
    | '/contact'
    | '/fencing'
    | '/painting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConcreteDrivewaysRoute: typeof ConcreteDrivewaysRoute
  ContactRoute: typeof ContactRoute
  FencingRoute: typeof FencingRoute
  PaintingRoute: typeof PaintingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete-driveways': {
      id: '/concrete-driveways'
      path: '/concrete-driveways'
      fullPath: '/concrete-driveways'
      preLoaderRoute: typeof ConcreteDrivewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fencing': {
      id: '/fencing'
      path: '/fencing'
      fullPath: '/fencing'
      preLoaderRoute: typeof FencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painting': {
      id: '/painting'
      path: '/painting'
      fullPath: '/painting'
      preLoaderRoute: typeof PaintingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConcreteDrivewaysRoute: ConcreteDrivewaysRoute,
  ContactRoute: ContactRoute,
  FencingRoute: FencingRoute,
  PaintingRoute: PaintingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
